# C.2 ndarray 객체

In [1]:
import numpy as np

## C.2.1 arange 메서드

In [2]:
np.arange(3)

array([0, 1, 2])

In [3]:
np.arange(2, 6)

array([2, 3, 4, 5])

In [4]:
np.arange(start = 2, stop = 6)

array([2, 3, 4, 5])

In [5]:
np.arange(start = 0, stop = 111, step = 10)

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110])

In [6]:
tens = np.arange(start = 0, stop = 111, step = 10)

## C.2.2 ndarray 객체의 속성

In [7]:
tens.shape

(12,)

In [8]:
tens.ndim

1

In [9]:
tens.size

12

## C.2.3 reshape 메서드

In [10]:
tens

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110])

In [11]:
tens.reshape(4, 3)

array([[  0,  10,  20],
       [ 30,  40,  50],
       [ 60,  70,  80],
       [ 90, 100, 110]])

In [12]:
tens.reshape(4, 3).ndim

2

In [13]:
tens.reshape(2, 6)

array([[  0,  10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100, 110]])

In [14]:
tens.reshape(2, 5)

ValueError: cannot reshape array of size 12 into shape (2,5)

In [15]:
tens.reshape(2, 3, 2)

array([[[  0,  10],
        [ 20,  30],
        [ 40,  50]],

       [[ 60,  70],
        [ 80,  90],
        [100, 110]]])

In [16]:
tens.reshape(2, 3, 2).ndim

3

In [17]:
tens.reshape(2, -1)

array([[  0,  10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100, 110]])

In [18]:
tens.reshape(2, -1, 2)

array([[[  0,  10],
        [ 20,  30],
        [ 40,  50]],

       [[ 60,  70],
        [ 80,  90],
        [100, 110]]])

## C.2.4 randint 함수

In [19]:
np.random.randint(5)

1

In [20]:
np.random.randint(1, 10)

3

In [21]:
np.random.randint(1, 10, 3)

array([1, 1, 9])

In [22]:
np.random.randint(1, 10, [3])

array([2, 6, 1])

In [23]:
np.random.randint(1, 10, [3, 5])

array([[6, 3, 8, 7, 6],
       [8, 1, 5, 5, 7],
       [7, 6, 3, 2, 1]])

## C.2.5 randn 함수

In [24]:
np.random.randn(3)

array([ 1.67658384, -1.05860167, -1.42641176])

In [25]:
np.random.randn(2, 4)

array([[-0.76866623,  0.87848456,  1.35702096,  0.16849181],
       [-0.56814378, -0.13010028, -1.17639784,  0.65073416]])

In [30]:
np.random.randn(2, 4, 3)

array([[[ 0.65199935,  0.64360149, -0.35661454],
        [ 1.32089981, -0.54727642, -0.89419161],
        [ 1.39818109,  0.09864683,  0.18492125],
        [-0.7265768 , -0.22893182,  0.99778759]],

       [[ 1.94208936,  1.41678737, -0.46784409],
        [ 0.33663641,  0.03957774,  0.68272607],
        [ 0.4806167 ,  0.52766848,  0.25761397],
        [ 0.65039129, -0.04511077,  0.22099265]]])

# C.3 nan 객체

In [27]:
np.nan

nan

In [28]:
np.nan == 5

False

In [29]:
np.nan == np.nan

False